;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        company-complete
        dabbrev-expand
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        forward-sexp
        indent-for-tab-command
        kill-region
        markdown-outdent-or-delete
        moving-home
        org-end-of-line
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        suspend-frame
        ))
