;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        comment-dwim
        company-complete
        dabbrev-expand
        dired-unmark-backward
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        forward-sexp
        indent-for-tab-command
        kill-region
        lsp-ui-doc--handle-mouse-movement
        markdown-beginning-of-line
        markdown-cycle
        markdown-end-of-line
        markdown-outdent-or-delete
        moving-home
        org-beginning-of-line
        org-end-of-line
        org-force-cycle-archived
        org-kill-line
        org-self-insert-command
        swiper
        wdired--self-insert
        wdired-finish-edit
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        suspend-frame
        ))
