;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        company-complete
        dabbrev-expand
        electric-pair-delete-pair
        kill-region
        markdown-outdent-or-delete
        moving-home
        ))

(setq mc/cmds-to-run-once
      '(
        ))
